// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEEZt8XzkKqnw8ck5NaWVpxFzIZK5Ruwc',
    appId: '1:439707945451:web:20d000fbf732694e7af1ae',
    messagingSenderId: '439707945451',
    projectId: 'carrito-aaf77',
    authDomain: 'carrito-aaf77.firebaseapp.com',
    storageBucket: 'carrito-aaf77.firebasestorage.app',
    measurementId: 'G-TW3HM5LC5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5PQHQERMAoBQ3VTbriBG8fzigpSyM9lY',
    appId: '1:439707945451:android:76164a48f75cf28a7af1ae',
    messagingSenderId: '439707945451',
    projectId: 'carrito-aaf77',
    storageBucket: 'carrito-aaf77.firebasestorage.app',
  );
}
